services:
  app:
    build: .
    container_name: lqd_app
    working_dir: /var/www/src
    volumes:
      - ./src:/var/www/src            # <-- aqui estava /var/www/html
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: lqd_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/src            # <-- garanta esse volume no web também
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: lqd_db
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "33060:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
